Vagrant.configure("2") do |config|

    config.vm.provision "shell", inline: "echo Welcome to Minio World"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"

    config.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    config.vm.define "loadbalancer" do |loadbalancer|
      loadbalancer.vm.box = "bento/ubuntu-20.04"
      loadbalancer.vm.network "private_network", ip: "192.168.30.100"
      loadbalancer.vm.hostname="loadbalancer"
      loadbalancer.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "loadbalancer"
            vb.memory = "512"
            vb.cpus= 1
        end
    end

    config.vm.define "minio1" do |minio1|
      minio1.vm.box = "bento/ubuntu-20.04"
      minio1.vm.network "private_network", ip: "192.168.25.100"
      minio1.vm.hostname="minio1"
      minio1.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "minio1"
            vb.memory = "512"
            vb.cpus= 1
        end
    end

    config.vm.define "minio2" do |minio2|
      minio2.vm.box = "bento/ubuntu-20.04"
      minio2.vm.network "private_network", ip: "192.168.25.200"
      minio2.vm.hostname="minio2"
      minio2.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "minio2"
            vb.memory = "512"
            vb.cpus= 1
        end
    end

end
